version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4-xenial
    ports:
      - 27017:27017
    networks:
      - java_network
  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - java_network
  java-docker-network:
    container_name: java-docker-network
    image: adetmarhadi/java-docker-network:1.0
    ports:
      - 8080:8080
    networks:
      - java_network
    depends_on:
      - mongo
      - redis
    environment:
      - NAME=Tataz
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  java_network:
    name: java_network